AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying Image Recognition API.

Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
  PollerAPI:
    Properties:
      Body:
        basePath: /Demo
        definitions:
          Empty:
            title: Empty Schema
            type: object
        info:
          title: CreateStateMachineAndTokenAPI
          version: '2019-03-01T09:15:33Z'
        paths:
          /CreateStateMachineAndToken:
            get:
              parameters:
              - in: query
                name: ExecutionArn
                required: true
                type: string
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                  schema:
                    $ref: '#/definitions/Empty'
              x-amazon-apigateway-integration:
                contentHandling: CONVERT_TO_TEXT
                httpMethod: POST
                passthroughBehavior: when_no_match
                responses:
                  default:
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    statusCode: '200'
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ImageRecognition_GetActivityStatus/invocations
            options:
              consumes:
              - application/json
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
                  schema:
                    $ref: '#/definitions/Empty'
              x-amazon-apigateway-integration:
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
                      method.response.header.Access-Control-Allow-Methods: '''POST,OPTIONS'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    statusCode: '200'
                type: mock
            post:
              parameters:
              - in: query
                name: Country
                required: false
                type: string
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                  schema:
                    $ref: '#/definitions/Empty'
              x-amazon-apigateway-integration:
                contentHandling: CONVERT_TO_TEXT
                httpMethod: POST
                passthroughBehavior: when_no_match
                responses:
                  default:
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    statusCode: '200'
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:CreateStateMachineAndToken/invocations
        schemes:
        - https
        swagger: '2.0'
      Description: To kick stepfunctions off.
      Name: CreateStateMachineAndTokenAPI
    Type: AWS::ApiGateway::RestApi
  ApiStage:
    Properties:
      DeploymentId:
        Ref: ApiDeployment
      RestApiId:
        Ref: PollerAPI
      StageName: ImageRecognition
    Type: AWS::ApiGateway::Stage
  ApiDeployment:
    Properties:
      Description: A deployment of the PollerAPI
      RestApiId:
        Ref: PollerAPI
    Type: AWS::ApiGateway::Deployment
  CreateStateMachineAndToken:
    Properties:
      CodeUri: ../code/
      Description: 'ImageRecognition: Lambda function to Create StateMachine And Token'
      Environment:
        Variables:
          stepfunctions_arn:
            Fn::Sub: arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:ImageRecognitionREST
          worker_arn:
            Fn::Sub: arn:aws:states:${AWS::Region}:${AWS::AccountId}:activity:OpenConnection
      FunctionName: CreateStateMachineAndToken
      Handler: createStateMachineAndToken.lambda_handler
      Role:
        Fn::GetAtt:
        - MyLambdaRole
        - Arn
      Runtime: python3.7
    Type: AWS::Serverless::Function
  RecognitionStateMachine:
    Properties:
      DefinitionString:
        Fn::Sub: |-
          {
            "Comment": "ImageRecognitionStateMachine",
            "StartAt": "RunImageRecognition",
            "States": {
                      "RunImageRecognition": {
                      "Type": "Task",
                      "Resource":"arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ImageRecognition-Rekognition",
                      "Next" : "IssueCallback"
                      },
                       "IssueCallback": {
                        "Type": "Task",
                        "Parameters": {
                          "myArn.$":"$$.Execution.Id",
                          "myPayload.$":"$"
                        },
                        "Resource":"arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SendMessageToClient",
                        "Retry": [
                          {
                        "ErrorEquals": ["DynamoRecordDoesNotExist"],
                        "IntervalSeconds": 5,
                        "MaxAttempts": 5,
                        "BackoffRate": 2.0
                      }
                        ],
                        "End":true
                      }
            }
          }
      RoleArn:
        Fn::GetAtt:
        - StatesExecutionRole
        - Arn
      StateMachineName: ImageRecognitionREST
    Type: AWS::StepFunctions::StateMachine
  RunImageRecognition:
    Properties:
      CodeUri: ../code/
      Description: 'ImageRecognition: Lambda function to run image recognition'
      Environment:
        Variables:
          athena_database: default
          athena_query: SELECT * FROM default.tweets where tweets.country=
          athena_table: tweets
          create_tweets_table: CREATE EXTERNAL TABLE IF NOT EXISTS default.tweets(   id bigint COMMENT 'Tweet ID',    text string COMMENT 'Tweet text',    created timestamp COMMENT 'Tweet create timestamp',    screen_name string COMMENT 'Tweet screen_name',   screen_name_followers_count int COMMENT 'Tweet screen_name follower count',   place string COMMENT 'Location full name',   country string COMMENT 'Location country',   retweet_count int COMMENT 'Retweet count',    favorite_count int COMMENT 'Favorite count') ROW FORMAT SERDE    'org.openx.data.jsonserde.JsonSerDe'  WITH SERDEPROPERTIES (    'paths'='id,text,created,screen_name,screen_name_followers_count,place_fullname,country,retweet_count,favorite_count')  STORED AS INPUTFORMAT    'org.apache.hadoop.mapred.TextInputFormat'  OUTPUTFORMAT    'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat' LOCATION   's3://aws-vpa-tweets/tweets/'
          region_name:
            Fn::Sub: ${AWS::Region}
          s3_output_location:
            Fn::Sub: s3://${ImageRecognitionBucket}
      FunctionName: ImageRecognition-Rekognition
      Handler: runImageRecognition.lambda_handler
      Role:
        Fn::GetAtt:
        - ImageRecognitionRole
        - Arn
      Runtime: python3.7
      Timeout: 300
    Type: AWS::Serverless::Function
  UpdateClientFunction:
    Properties:
      CodeUri: ../code/
      Description: update connected client with StepFunction outcome.
      Environment:
        Variables:
          callbackURL:
            Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${ImageRecognitionStage}
          stepfunctions_arn:
            Fn::Sub: arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:ImageRecognitionREST
      FunctionName: SendMessageToClient
      Handler: sendMessageToClient.lambda_handler
      Role:
        Fn::GetAtt:
        - ImageRecognitionRole
        - Arn
      Runtime: python3.7
    Type: AWS::Serverless::Function
  MyApi:
    Properties:
      ApiKeySelectionExpression: $request.header.x-api-key
      Name: ImageRecognition-WebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
    Type: AWS::ApiGatewayV2::Api
  WSConnectFunction:
    Properties:
      CodeUri:
        Bucket: ../code/
      Description: Function triggers OpenConnection is triggered by the websocket API
      Environment:
        Variables:
          stepfunctions_arn:
            Fn::Sub: arn:aws:states:${AWS::Region}:${AWS::AccountId}:execution:ImageRecognitionREST
      FunctionName: ImageRecognition_OpenConnection
      Handler: openConnection.lambda_handler
      Role:
        Fn::GetAtt:
        - ImageRecognitionRole
        - Arn
      Runtime: python3.7
    Type: AWS::Serverless::Function
  ImageRecognitionGetActivityStatus:
    Properties:
      CodeUri:
        Bucket: ../code/
      Description: 'ImageRecognition: Lambda function to GetActivityStatus or Results'
      FunctionName: ImageRecognition_GetActivityStatus
      Handler: getActivityStatus.lambda_handler
      Role:
        Fn::GetAtt:
        - MyLambdaRole
        - Arn
      Runtime: python3.7
    Type: AWS::Serverless::Function
  StatesExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - Fn::Sub: states.${AWS::Region}.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - lambda:InvokeFunction
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: StatesExecutionPolicy
    Type: AWS::IAM::Role
  StepFunctionLambdaPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - states:DescribeExecution
          - states:StartExecution
          - states:GetActivityTask
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      PolicyName: AllowPostToConnection
      Roles:
      - Ref: MyLambdaRole
    Type: AWS::IAM::Policy